### ISSUE TITLE
Where to put the app description

### ISSUE THREAD

**Issue by dataubc** [UBC-MDS/DSCI_532_Group_113_Overdose_R#11]
Hello tema, 

I am not sure that is best way to put the app description ?
<img width="1680" alt="Screen Shot 2019-12-12 at 3 52 47 PM" src="https://user-images.githubusercontent.com/54875834/70758431-c83a8680-1cf7-11ea-9158-1e8fbafd43c6.png">

**Comment by AndresPitta** [comment]
Hi,
Mohammed, I think it does not look bad. 

However, if you want to put it somewhere else try it, we trust you. 
I can now pull request the new changes if you want to keep working on that version.

Let us know what you decide.
Thanks for the work.

**Comment by dataubc** [comment]
I am still not happy with it, will try to make it better
