### ISSUE TITLE
Work in progress

### ISSUE THREAD

**Issue by HanyingZhang** [UBC-MDS/DSCI_532_Group_113_Overdose_R#2]
- current progress on creating plots in R

    These two plots will be included in the future R dashboard.

    The first one is the heatmap comparing the number of two-drug combinations found in the deceased. The second one, concerning the victims, is showing the age, gender and race distributions of the victims of different drugs.

    We plan to put these two plots in different tabs in the dashboard, so the users can explore the overdose issue from different aspects.

![screenshot](https://user-images.githubusercontent.com/35021819/70366719-3ee60880-184e-11ea-8c30-c86160ea4a33.png)

**Comment by AndresPitta** [comment]
Thanks for the update, Hanying.
